version: "3.9"
   
services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017

  web:
    build:
      context: .
      dockerfile: build/package/Dockerfile
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://username:password@db:27017/
    depends_on:
      - db
    ports:
      - "8080:8080"